name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: youtube-playlist
        uses: xxb1s/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: ""
          plugin_music: yes
          plugin_music_playlist: >-
            https://music.youtube.com/playlist?list=PLbwacYKjVjwXBWvqldBhODbI3N9g6mC1V&feature=share
